targets:
  $default:
    builders:
      json_serializable:json_serializable:
        options:
          # Options for json_serializable
          explicit_to_json: true
          include_if_null: false
          field_rename: snake
        generate_for:
          - lib/features/**/domain/**.dart
          - lib/features/**/data/models/**.dart
          - lib/features/**/presentation/models/**.dart
          - lib/features/**/models/**.dart

      mockito:mockBuilder:
        options:
          # Options for mockito
          generate_for:
            - test/**.dart
