// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Ejemplo: Clase de datos para pasar información compleja
/// 
/// Pigeon puede serializar clases de datos automáticamente
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeviceInfo {
  var model: String
  var osVersion: String
  var deviceId: String
  var brand: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceInfo? {
    let model = pigeonVar_list[0] as! String
    let osVersion = pigeonVar_list[1] as! String
    let deviceId = pigeonVar_list[2] as! String
    let brand: String? = nilOrValue(pigeonVar_list[3])

    return DeviceInfo(
      model: model,
      osVersion: osVersion,
      deviceId: deviceId,
      brand: brand
    )
  }
  func toList() -> [Any?] {
    return [
      model,
      osVersion,
      deviceId,
      brand,
    ]
  }
}

private class PigeonApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return DeviceInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DeviceInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonApiPigeonCodecWriter(data: data)
  }
}

class PigeonApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonApiPigeonCodec(readerWriter: PigeonApiPigeonCodecReaderWriter())
}

/// Ejemplo: API para obtener información del dispositivo
/// 
/// Este es un ejemplo básico. Puedes agregar más APIs según tus necesidades.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceInfoApi {
  /// Obtiene el modelo del dispositivo
  func getDeviceModel() throws -> String
  /// Obtiene la versión del sistema operativo
  func getOsVersion() throws -> String
  /// Obtiene el ID único del dispositivo
  func getDeviceId() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceInfoApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `DeviceInfoApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceInfoApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Obtiene el modelo del dispositivo
    let getDeviceModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.goncook.DeviceInfoApi.getDeviceModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceModelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceModel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceModelChannel.setMessageHandler(nil)
    }
    /// Obtiene la versión del sistema operativo
    let getOsVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.goncook.DeviceInfoApi.getOsVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOsVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getOsVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getOsVersionChannel.setMessageHandler(nil)
    }
    /// Obtiene el ID único del dispositivo
    let getDeviceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.goncook.DeviceInfoApi.getDeviceId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceIdChannel.setMessageHandler(nil)
    }
  }
}
/// Ejemplo: API para operaciones de almacenamiento seguro
/// 
/// Permite almacenar y recuperar datos de forma segura desde código nativo
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecureStorageApi {
  /// Guarda un valor de forma segura
  /// 
  /// [key] - Clave para identificar el valor
  /// [value] - Valor a guardar
  /// Retorna true si se guardó correctamente
  func saveSecureValue(key: String, value: String) throws -> Bool
  /// Recupera un valor guardado de forma segura
  /// 
  /// [key] - Clave del valor a recuperar
  /// Retorna el valor o null si no existe
  func getSecureValue(key: String) throws -> String?
  /// Elimina un valor guardado
  /// 
  /// [key] - Clave del valor a eliminar
  /// Retorna true si se eliminó correctamente
  func deleteSecureValue(key: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecureStorageApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `SecureStorageApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecureStorageApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Guarda un valor de forma segura
    /// 
    /// [key] - Clave para identificar el valor
    /// [value] - Valor a guardar
    /// Retorna true si se guardó correctamente
    let saveSecureValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.goncook.SecureStorageApi.saveSecureValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveSecureValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        do {
          let result = try api.saveSecureValue(key: keyArg, value: valueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveSecureValueChannel.setMessageHandler(nil)
    }
    /// Recupera un valor guardado de forma segura
    /// 
    /// [key] - Clave del valor a recuperar
    /// Retorna el valor o null si no existe
    let getSecureValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.goncook.SecureStorageApi.getSecureValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSecureValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.getSecureValue(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSecureValueChannel.setMessageHandler(nil)
    }
    /// Elimina un valor guardado
    /// 
    /// [key] - Clave del valor a eliminar
    /// Retorna true si se eliminó correctamente
    let deleteSecureValueChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.goncook.SecureStorageApi.deleteSecureValue\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteSecureValueChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.deleteSecureValue(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteSecureValueChannel.setMessageHandler(nil)
    }
  }
}
/// Ejemplo: API bidireccional para notificaciones
/// 
/// Permite que el código nativo envíe eventos a Flutter
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NotificationApiProtocol {
  /// Notifica a Flutter cuando llega una notificación push
  /// 
  /// [title] - Título de la notificación
  /// [body] - Cuerpo de la notificación
  /// [data] - Datos adicionales en formato JSON
  func onNotificationReceived(title titleArg: String, body bodyArg: String, data dataArg: [String: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class NotificationApi: NotificationApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonApiPigeonCodec {
    return PigeonApiPigeonCodec.shared
  }
  /// Notifica a Flutter cuando llega una notificación push
  /// 
  /// [title] - Título de la notificación
  /// [body] - Cuerpo de la notificación
  /// [data] - Datos adicionales en formato JSON
  func onNotificationReceived(title titleArg: String, body bodyArg: String, data dataArg: [String: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.goncook.NotificationApi.onNotificationReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([titleArg, bodyArg, dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// API que retorna objetos complejos
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceInfoComplexApi {
  /// Obtiene información completa del dispositivo
  func getDeviceInfo() throws -> DeviceInfo
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceInfoComplexApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `DeviceInfoComplexApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceInfoComplexApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Obtiene información completa del dispositivo
    let getDeviceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.goncook.DeviceInfoComplexApi.getDeviceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceInfoChannel.setMessageHandler(nil)
    }
  }
}
