// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.ngonzano.goncook

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Ejemplo: Clase de datos para pasar información compleja
 * 
 * Pigeon puede serializar clases de datos automáticamente
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceInfo (
  val model: String,
  val osVersion: String,
  val deviceId: String,
  val brand: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceInfo {
      val model = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String
      val deviceId = pigeonVar_list[2] as String
      val brand = pigeonVar_list[3] as String?
      return DeviceInfo(model, osVersion, deviceId, brand)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      model,
      osVersion,
      deviceId,
      brand,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DeviceInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DeviceInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Ejemplo: API para obtener información del dispositivo
 * 
 * Este es un ejemplo básico. Puedes agregar más APIs según tus necesidades.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DeviceInfoApi {
  /** Obtiene el modelo del dispositivo */
  fun getDeviceModel(): String
  /** Obtiene la versión del sistema operativo */
  fun getOsVersion(): String
  /** Obtiene el ID único del dispositivo */
  fun getDeviceId(): String

  companion object {
    /** The codec used by DeviceInfoApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `DeviceInfoApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceInfoApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.goncook.DeviceInfoApi.getDeviceModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceModel())
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.goncook.DeviceInfoApi.getOsVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getOsVersion())
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.goncook.DeviceInfoApi.getDeviceId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceId())
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Ejemplo: API para operaciones de almacenamiento seguro
 * 
 * Permite almacenar y recuperar datos de forma segura desde código nativo
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SecureStorageApi {
  /**
   * Guarda un valor de forma segura
   * 
   * [key] - Clave para identificar el valor
   * [value] - Valor a guardar
   * Retorna true si se guardó correctamente
   */
  fun saveSecureValue(key: String, value: String): Boolean
  /**
   * Recupera un valor guardado de forma segura
   * 
   * [key] - Clave del valor a recuperar
   * Retorna el valor o null si no existe
   */
  fun getSecureValue(key: String): String?
  /**
   * Elimina un valor guardado
   * 
   * [key] - Clave del valor a eliminar
   * Retorna true si se eliminó correctamente
   */
  fun deleteSecureValue(key: String): Boolean

  companion object {
    /** The codec used by SecureStorageApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `SecureStorageApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SecureStorageApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.goncook.SecureStorageApi.saveSecureValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.saveSecureValue(keyArg, valueArg))
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.goncook.SecureStorageApi.getSecureValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getSecureValue(keyArg))
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.goncook.SecureStorageApi.deleteSecureValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.deleteSecureValue(keyArg))
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Ejemplo: API bidireccional para notificaciones
 * 
 * Permite que el código nativo envíe eventos a Flutter
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class NotificationApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NotificationApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
  }
  /**
   * Notifica a Flutter cuando llega una notificación push
   * 
   * [title] - Título de la notificación
   * [body] - Cuerpo de la notificación
   * [data] - Datos adicionales en formato JSON
   */
  fun onNotificationReceived(titleArg: String, bodyArg: String, dataArg: Map<String, Any?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.goncook.NotificationApi.onNotificationReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(titleArg, bodyArg, dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * API que retorna objetos complejos
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DeviceInfoComplexApi {
  /** Obtiene información completa del dispositivo */
  fun getDeviceInfo(): DeviceInfo

  companion object {
    /** The codec used by DeviceInfoComplexApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `DeviceInfoComplexApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceInfoComplexApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.goncook.DeviceInfoComplexApi.getDeviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceInfo())
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
