// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'payu_checkout_response_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PayuCheckoutResponseModel _$PayuCheckoutResponseModelFromJson(
  Map<String, dynamic> json,
) => PayuCheckoutResponseModel(
  merchantId: json['merchantId'] as String?,
  merchantName: json['merchant_name'] as String?,
  merchantAddress: json['merchant_address'] as String?,
  telephone: json['telephone'] as String?,
  merchantUrl: json['merchant_url'] as String?,
  transactionState: json['transactionState'] as String?,
  lapTransactionState: json['lapTransactionState'] as String?,
  message: json['message'] as String?,
  referenceCode: json['referenceCode'] as String?,
  referencePol: json['reference_pol'] as String?,
  transactionId: json['transactionId'] as String?,
  description: json['description'] as String?,
  trazabilityCode: json['trazabilityCode'] as String?,
  cus: json['cus'] as String?,
  orderLanguage: json['orderLanguage'] as String?,
  extra1: json['extra1'] as String?,
  extra2: json['extra2'] as String?,
  extra3: json['extra3'] as String?,
  polTransactionState: json['polTransactionState'] as String?,
  signature: json['signature'] as String?,
  polResponseCode: json['polResponseCode'] as String?,
  lapResponseCode: json['lapResponseCode'] as String?,
  risk: json['risk'] as String?,
  polPaymentMethod: json['polPaymentMethod'] as String?,
  lapPaymentMethod: json['lapPaymentMethod'] as String?,
  polPaymentMethodType: json['polPaymentMethodType'] as String?,
  lapPaymentMethodType: json['lapPaymentMethodType'] as String?,
  installmentsNumber: json['installmentsNumber'] as String?,
  txValue: json['TX_VALUE'] as String?,
  txTax: json['TX_TAX'] as String?,
  currency: json['currency'] as String?,
  lng: json['lng'] as String?,
  pseCycle: json['pseCycle'] as String?,
  buyerEmail: json['buyerEmail'] as String?,
  pseBank: json['pseBank'] as String?,
  pseReference1: json['pseReference1'] as String?,
  pseReference2: json['pseReference2'] as String?,
  pseReference3: json['pseReference3'] as String?,
  authorizationCode: json['authorizationCode'] as String?,
  khipuBank: json['khipuBank'] as String?,
  txAdministrativeFee: json['TX_ADMINISTRATIVE_FEE'] as String?,
  txTaxAdministrativeFee: json['TX_TAX_ADMINISTRATIVE_FEE'] as String?,
  txTaxAdministrativeFeeReturnBase:
      json['TX_TAX_ADMINISTRATIVE_FEE_RETURN_BASE'] as String?,
  processingDate: json['processingDate'] as String?,
);

Map<String, dynamic> _$PayuCheckoutResponseModelToJson(
  PayuCheckoutResponseModel instance,
) => <String, dynamic>{
  'merchantId': instance.merchantId,
  'merchant_name': instance.merchantName,
  'merchant_address': instance.merchantAddress,
  'telephone': instance.telephone,
  'merchant_url': instance.merchantUrl,
  'transactionState': instance.transactionState,
  'lapTransactionState': instance.lapTransactionState,
  'message': instance.message,
  'referenceCode': instance.referenceCode,
  'reference_pol': instance.referencePol,
  'transactionId': instance.transactionId,
  'description': instance.description,
  'trazabilityCode': instance.trazabilityCode,
  'cus': instance.cus,
  'orderLanguage': instance.orderLanguage,
  'extra1': instance.extra1,
  'extra2': instance.extra2,
  'extra3': instance.extra3,
  'polTransactionState': instance.polTransactionState,
  'signature': instance.signature,
  'polResponseCode': instance.polResponseCode,
  'lapResponseCode': instance.lapResponseCode,
  'risk': instance.risk,
  'polPaymentMethod': instance.polPaymentMethod,
  'lapPaymentMethod': instance.lapPaymentMethod,
  'polPaymentMethodType': instance.polPaymentMethodType,
  'lapPaymentMethodType': instance.lapPaymentMethodType,
  'installmentsNumber': instance.installmentsNumber,
  'TX_VALUE': instance.txValue,
  'TX_TAX': instance.txTax,
  'currency': instance.currency,
  'lng': instance.lng,
  'pseCycle': instance.pseCycle,
  'buyerEmail': instance.buyerEmail,
  'pseBank': instance.pseBank,
  'pseReference1': instance.pseReference1,
  'pseReference2': instance.pseReference2,
  'pseReference3': instance.pseReference3,
  'authorizationCode': instance.authorizationCode,
  'khipuBank': instance.khipuBank,
  'TX_ADMINISTRATIVE_FEE': instance.txAdministrativeFee,
  'TX_TAX_ADMINISTRATIVE_FEE': instance.txTaxAdministrativeFee,
  'TX_TAX_ADMINISTRATIVE_FEE_RETURN_BASE':
      instance.txTaxAdministrativeFeeReturnBase,
  'processingDate': instance.processingDate,
};
