// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This configuration only supports iOS and Android platforms.
/// Other platforms (web, macOS, windows, linux) will throw an [UnsupportedError].
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for web. '
        'This app only supports iOS and Android platforms.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for macOS. '
          'This app only supports iOS and Android platforms.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for windows. '
          'This app only supports iOS and Android platforms.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for linux. '
          'This app only supports iOS and Android platforms.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'This app only supports iOS and Android platforms.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNayOOzzxC_RGCI5uMG30yepUoEVF9fx8',
    appId: '1:615495880468:android:8b8e1ab4ff1668b5123c01',
    messagingSenderId: '615495880468',
    projectId: 'recetas-6a516',
    storageBucket: 'recetas-6a516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_OnAfqierQR7ZRsatsc4LLfjvK4jtKY',
    appId: '1:615495880468:ios:7cbbee23e43f017b123c01',
    messagingSenderId: '615495880468',
    projectId: 'recetas-6a516',
    storageBucket: 'recetas-6a516.firebasestorage.app',
    androidClientId: '615495880468-anvvckm3725v8gv74cvpu188m5q2btqu.apps.googleusercontent.com',
    iosClientId: '615495880468-vaqqmb8h3ihto2np80mbhthuvtovjilu.apps.googleusercontent.com',
    iosBundleId: 'com.ngonzano.comidaperuana',
  );
}
