// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TwKGOBTj907uyzT_FrS7AzwehOc03PY',
    appId: '1:86173141894:android:eedf4594ce8972ef303a07',
    messagingSenderId: '86173141894',
    projectId: 'goncook-55c25',
    storageBucket: 'goncook-55c25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8o0JRbRLZ1pRurX9L3kCi3Z6OKeG33qU',
    appId: '1:86173141894:ios:91c226e38708e256303a07',
    messagingSenderId: '86173141894',
    projectId: 'goncook-55c25',
    storageBucket: 'goncook-55c25.firebasestorage.app',
    androidClientId: '86173141894-cr4cef7n6ldak339nr23j50h8v38qk1l.apps.googleusercontent.com',
    iosClientId: '86173141894-mbloi0319dgj0pscqetnukgab9tvc4ru.apps.googleusercontent.com',
    iosBundleId: 'com.ngonzano.goncook',
  );

}