// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8NWB7yAWX2GBM6yxK3hbRg5jo4mVBiRo',
    appId: '1:615495880468:web:f0ff3b84d618d6d4123c01',
    messagingSenderId: '615495880468',
    projectId: 'recetas-6a516',
    authDomain: 'recetas-6a516.firebaseapp.com',
    storageBucket: 'recetas-6a516.firebasestorage.app',
    measurementId: 'G-487HGQDD2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNayOOzzxC_RGCI5uMG30yepUoEVF9fx8',
    appId: '1:615495880468:android:8b8e1ab4ff1668b5123c01',
    messagingSenderId: '615495880468',
    projectId: 'recetas-6a516',
    storageBucket: 'recetas-6a516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_OnAfqierQR7ZRsatsc4LLfjvK4jtKY',
    appId: '1:615495880468:ios:7cbbee23e43f017b123c01',
    messagingSenderId: '615495880468',
    projectId: 'recetas-6a516',
    storageBucket: 'recetas-6a516.firebasestorage.app',
    androidClientId:
        '615495880468-ppspts5tledjg2qm5qq45duqibv534nm.apps.googleusercontent.com',
    iosClientId:
        '615495880468-vaqqmb8h3ihto2np80mbhthuvtovjilu.apps.googleusercontent.com',
    iosBundleId: 'com.ngonzano.comidaperuana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh_OnAfqierQR7ZRsatsc4LLfjvK4jtKY',
    appId: '1:615495880468:ios:7cbbee23e43f017b123c01',
    messagingSenderId: '615495880468',
    projectId: 'recetas-6a516',
    storageBucket: 'recetas-6a516.firebasestorage.app',
    androidClientId:
        '615495880468-ppspts5tledjg2qm5qq45duqibv534nm.apps.googleusercontent.com',
    iosClientId:
        '615495880468-vaqqmb8h3ihto2np80mbhthuvtovjilu.apps.googleusercontent.com',
    iosBundleId: 'com.ngonzano.comidaperuana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8NWB7yAWX2GBM6yxK3hbRg5jo4mVBiRo',
    appId: '1:615495880468:web:fe2dc33192ffa724123c01',
    messagingSenderId: '615495880468',
    projectId: 'recetas-6a516',
    authDomain: 'recetas-6a516.firebaseapp.com',
    storageBucket: 'recetas-6a516.firebasestorage.app',
    measurementId: 'G-PZT5G6GJ1Y',
  );
}
