// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'payu_checkout_response_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PayuCheckoutResponseModel _$PayuCheckoutResponseModelFromJson(
  Map<String, dynamic> json,
) => PayuCheckoutResponseModel(
  merchantId: json['merchant_id'] as String?,
  merchantName: json['merchant_name'] as String?,
  merchantAddress: json['merchant_address'] as String?,
  telephone: json['telephone'] as String?,
  merchantUrl: json['merchant_url'] as String?,
  transactionState: json['transaction_state'] as String?,
  lapTransactionState: json['lap_transaction_state'] as String?,
  message: json['message'] as String?,
  referenceCode: json['reference_code'] as String?,
  referencePol: json['reference_pol'] as String?,
  transactionId: json['transaction_id'] as String?,
  description: json['description'] as String?,
  trazabilityCode: json['trazability_code'] as String?,
  cus: json['cus'] as String?,
  orderLanguage: json['order_language'] as String?,
  extra1: json['extra1'] as String?,
  extra2: json['extra2'] as String?,
  extra3: json['extra3'] as String?,
  polTransactionState: json['pol_transaction_state'] as String?,
  signature: json['signature'] as String?,
  polResponseCode: json['pol_response_code'] as String?,
  lapResponseCode: json['lap_response_code'] as String?,
  risk: json['risk'] as String?,
  polPaymentMethod: json['pol_payment_method'] as String?,
  lapPaymentMethod: json['lap_payment_method'] as String?,
  polPaymentMethodType: json['pol_payment_method_type'] as String?,
  lapPaymentMethodType: json['lap_payment_method_type'] as String?,
  installmentsNumber: json['installments_number'] as String?,
  txValue: json['TX_VALUE'] as String?,
  txTax: json['TX_TAX'] as String?,
  currency: json['currency'] as String?,
  lng: json['lng'] as String?,
  pseCycle: json['pse_cycle'] as String?,
  buyerEmail: json['buyer_email'] as String?,
  pseBank: json['pse_bank'] as String?,
  pseReference1: json['pse_reference1'] as String?,
  pseReference2: json['pse_reference2'] as String?,
  pseReference3: json['pse_reference3'] as String?,
  authorizationCode: json['authorization_code'] as String?,
  khipuBank: json['khipu_bank'] as String?,
  txAdministrativeFee: json['TX_ADMINISTRATIVE_FEE'] as String?,
  txTaxAdministrativeFee: json['TX_TAX_ADMINISTRATIVE_FEE'] as String?,
  txTaxAdministrativeFeeReturnBase:
      json['TX_TAX_ADMINISTRATIVE_FEE_RETURN_BASE'] as String?,
  processingDate: json['processing_date'] as String?,
);

Map<String, dynamic> _$PayuCheckoutResponseModelToJson(
  PayuCheckoutResponseModel instance,
) => <String, dynamic>{
  'merchant_id': ?instance.merchantId,
  'merchant_name': ?instance.merchantName,
  'merchant_address': ?instance.merchantAddress,
  'telephone': ?instance.telephone,
  'merchant_url': ?instance.merchantUrl,
  'transaction_state': ?instance.transactionState,
  'lap_transaction_state': ?instance.lapTransactionState,
  'message': ?instance.message,
  'reference_code': ?instance.referenceCode,
  'reference_pol': ?instance.referencePol,
  'transaction_id': ?instance.transactionId,
  'description': ?instance.description,
  'trazability_code': ?instance.trazabilityCode,
  'cus': ?instance.cus,
  'order_language': ?instance.orderLanguage,
  'extra1': ?instance.extra1,
  'extra2': ?instance.extra2,
  'extra3': ?instance.extra3,
  'pol_transaction_state': ?instance.polTransactionState,
  'signature': ?instance.signature,
  'pol_response_code': ?instance.polResponseCode,
  'lap_response_code': ?instance.lapResponseCode,
  'risk': ?instance.risk,
  'pol_payment_method': ?instance.polPaymentMethod,
  'lap_payment_method': ?instance.lapPaymentMethod,
  'pol_payment_method_type': ?instance.polPaymentMethodType,
  'lap_payment_method_type': ?instance.lapPaymentMethodType,
  'installments_number': ?instance.installmentsNumber,
  'TX_VALUE': ?instance.txValue,
  'TX_TAX': ?instance.txTax,
  'currency': ?instance.currency,
  'lng': ?instance.lng,
  'pse_cycle': ?instance.pseCycle,
  'buyer_email': ?instance.buyerEmail,
  'pse_bank': ?instance.pseBank,
  'pse_reference1': ?instance.pseReference1,
  'pse_reference2': ?instance.pseReference2,
  'pse_reference3': ?instance.pseReference3,
  'authorization_code': ?instance.authorizationCode,
  'khipu_bank': ?instance.khipuBank,
  'TX_ADMINISTRATIVE_FEE': ?instance.txAdministrativeFee,
  'TX_TAX_ADMINISTRATIVE_FEE': ?instance.txTaxAdministrativeFee,
  'TX_TAX_ADMINISTRATIVE_FEE_RETURN_BASE':
      ?instance.txTaxAdministrativeFeeReturnBase,
  'processing_date': ?instance.processingDate,
};
